2020 server upgrade

diff --git a/uesp-create-localkey b/uesp-create-localkey
--- a/uesp-create-localkey
+++ b/uesp-create-localkey
@@ -18,7 +18,7 @@ create_server_key()
 	KEYFILE="keys/$1-uesp-key"
 	PUBKEYFILE="$KEYFILE.pub"
 
-	ssh-keygen -q -t dsa -b 1024 -f $KEYFILE -C "$1.uesp.net" -N ""
+	ssh-keygen -q -t rsa -b 4096 -a 100 -f $KEYFILE -C "$1.uesp.net" -N ""
 	RESULT=$?
 	
 	if [ $RESULT != 0 ]
@@ -59,10 +59,41 @@ create_server_key()
 			echo "     ERROR: Failed to create directory '$HOMEPATH'!"
 		else
 			chown uespkey:uespkey "$HOMEPATH"
+			chmod 700 $HOMEPATH
 		fi
 	fi
 
-	cp -f $LOCALKEY $HOMEPATH/id_dsa
+	cp -f $KEYFILE $HOMEPATH/id_rsa
+	chown uespkey:uespkey $HOMEPATH/id_rsa
+	chmod 600 $HOMEPATH/id_rsa
+	
+	cp -f $KEYFILE /etc/uesp-keys/local-uesp-key
+	chown uespkey:uespkey /etc/uesp-keys/local-uesp-key
+	chmod 600 /etc/uesp-keys/local-uesp-key
+	
+	touch $HOMEPATH/authorized_keys
+	chmod 600 $HOMEPATH/authorized_keys
+	
+	HOMEPATH="/home/dave/.ssh"
+
+	if [ ! -d "$HOMEPATH" ]
+	then
+		mkdir -p "$HOMEPATH"
+
+		if [ $? != 0 ]
+		then
+			echo "     ERROR: Failed to create directory '$HOMEPATH'!"
+		else
+			chown dave:dave "$HOMEPATH"
+			chmod 700 $HOMEPATH
+		fi
+	fi
+
+	cp -f $KEYFILE $HOMEPATH/id_rsa
+	chown dave:dave $HOMEPATH/id_rsa
+	chmod 600 $HOMEPATH/id_rsa
+	touch $HOMEPATH/authorized_keys
+	chmod 600 $HOMEPATH/authorized_keys
 
 	cp -f $PUBKEYFILE $KEYPATH
 	cp -f $LOCALKEY $KEYPATH
diff --git a/uesp-install-denyhosts b/uesp-install-denyhosts
--- a/uesp-install-denyhosts
+++ b/uesp-install-denyhosts
@@ -2,65 +2,69 @@
 
 echo "Starting uesp-install-denyhosts..."
 
-pushd . > /dev/null
-cd denyhosts
+./uesp-yuminstall "python"
+./uesp-yuminstall "python-ipaddr"
 
-python setup.py install > /dev/null
+pushd denyhosts > /dev/null
+
+python setup.py install
 RESULT=$?
 
 if [ $RESULT != 0 ]
 then
 	echo "     ERROR: Failed to install the DenyHosts Python application!"
-	exit -1
-fi
-
-cp -f /usr/share/denyhosts/denyhosts.cfg-dist /usr/share/denyhosts/denyhosts.cfg
-RESULT=$?
-
-if [ $RESULT != 0 ]
-then
-	echo "     ERROR: Failed to create the DenyHosts configuration file!"
+	popd
 	exit -1
 fi
 
 HOSTNAME=`hostname`
-sed -i -e"s/denyhosts@localhost/denyhosts@$HOSTNAME/" /usr/share/denyhosts/denyhosts.cfg
+sed -i -e"s/^PURGE_DENY =.*/PURGE_DENY = 2w/" /etc/denyhosts.conf
+
+if [ $? != 0 ]
+then
+	echo "     WARNING: Failed to modify denyhosts PURGE_DENY setting!"
+fi
+
+sed -i -e"s/nobody@localhost/denyhosts@$HOSTNAME/" /etc/denyhosts.conf
 
 if [ $? != 0 ]
 then
 	echo "     WARNING: Failed to modify denyhosts send e-mail address!"
 fi
 
-cp -f /usr/share/denyhosts/daemon-control-dist /usr/share/denyhosts/daemon-control
+mv -f /usr/bin/daemon-control-dist /usr/bin/denyhosts-daemon-control
 RESULT=$?
 
 if [ $RESULT != 0 ]
 then
 	echo "     ERROR: Failed to create the DenyHosts daemon file!"
+	popd
 	exit -2
 fi
 
-chown root /usr/share/denyhosts/daemon-control
+chown root /usr/bin/denyhosts-daemon-control
 RESULT=$?
 
 if [ $RESULT != 0 ]
 then
 	echo "     ERROR: Failed to change the owner of the DenyHosts daemon-control file!"
+	popd
 	exit -3
 fi
 
-chmod 700 /usr/share/denyhosts/daemon-control
+chmod 700 /usr/bin/denyhosts-daemon-control
 RESULT=$?
 
 if [ $RESULT != 0 ]
 then
 	echo "     ERROR: Failed to change the permissions of the DenyHosts daemon-control file!"
+	popd
 	exit -4
 fi
 
 if [ ! -d /var/log/denyhosts ]
 then
-	mkdir /var/log/denyhosts
+	mkdir -p /var/log/denyhosts
 	RESULT=$?
 
 	if [ $RESULT != 0 ]
@@ -69,38 +73,45 @@ then
 	fi
 fi
 
-ln -f -s /usr/share/denyhosts/daemon-control /etc/init.d/denyhosts
+sed -i "s/^DAEMON_LOG =.*/DAEMON_LOG = \/var\/log\/denyhosts\/denyhosts.log/g" /etc/denyhosts.conf
+
+ln -fs /usr/bin/denyhosts-daemon-control /etc/init.d/denyhosts
 RESULT=$?
 
 if [ $RESULT != 0 ]
 then
 	echo "     ERROR: Failed to add DenyHosts startup script to '/etc/init.d/'!"
+	popd
 	exit -5
 fi
 
-/sbin/chkconfig --add denyhosts
+ln -fs /usr/bin/denyhosts.py /usr/sbin/denyhosts
 RESULT=$?
 
 if [ $RESULT != 0 ]
 then
-	echo "     ERROR: Failed to add DenyHosts startup script using chkconfig!"
+	echo "     ERROR: Failed to create /usr/sbin/denyhosts entry!"
+	popd
+	exit -5
+fi
+
+systemctl enable denyhosts
+RESULT=$?
+
+if [ $RESULT != 0 ]
+then
+	echo "     ERROR: Failed to add DenyHosts startup script using systemctl!"
+	popd
 	exit -6
 fi
 
-ln -fs /usr/share/denyhosts/denyhosts.cfg /etc/denyhosts.cfg
-RESULT=$?
-
-if [ $RESULT != 0 ]
-then
-	echo "     ERROR: Failed to create link to denyhosts.cfg in /etc/!"
-fi
-
-/etc/init.d/denyhosts restart > /dev/null
+systemctl start denyhosts
 RESULT=$?
 
 if [ $RESULT != 0 ]
 then
 	echo "     ERROR: Failed to start DenyHosts!"
+	popd
 	exit -8
 fi
 
diff --git a/uesp-install-wikidiff2 b/uesp-install-wikidiff2
--- a/uesp-install-wikidiff2
+++ b/uesp-install-wikidiff2
@@ -1,45 +1,87 @@
 #!/bin/sh
 
-make --quiet -C ./wikidiff2 2> /dev/null
+./uesp-yuminstall "libthai"
+./uesp-yuminstall "libthai-devel"
+
+pushd wikidiff2
+
+phpize
 RESULT=$?
 
 if [ $RESULT != 0 ]
 then
-	echo "     ERROR: 'make' failed to compile/link WikiDiff2!"
+	echo "     ERROR: 'make' failed to phpize WikiDiff2!"
+	popd
 	exit -1
 fi
 
-make --quiet -C ./wikidiff2 install 2> /dev/null
+./configure
+RESULT=$?
+
+if [ $RESULT != 0 ]
+then
+	echo "     ERROR: 'make' failed to configure WikiDiff2!"
+	popd
+	exit -2
+fi
+
+make --quiet 2> /dev/null
+RESULT=$?
+
+if [ $RESULT != 0 ]
+then
+	echo "     ERROR: 'make' failed to make WikiDiff2!"
+	popd
+	exit -3
+fi
+
+make --quiet install 2> /dev/null
 RESULT=$?
 
 if [ $RESULT != 0 ]
 then
 	echo "     ERROR: 'make' failed to install WikiDiff2!"
-	exit -2
+	popd
+	exit -4
 fi
 
-if [ ! -f /usr/lib64/php/modules/php_wikidiff2.so ]
-then
-	echo "     ERROR: Failed to install the WikiDiff2 PHP extension!"
-	exit -1
-fi
+cp -f ./modules/wikidiff2.so /usr/lib64/php/modules/
 
-cp -f ./wikidiff2/php_wikidiff2.ini /etc/php.d
 RESULT=$?
 
-if [ $RESULT !=  0 ] || [ ! -f /etc/php.d/php_wikidiff2.ini ]
+if [ $RESULT != 0 ]
 then
-	echo "     ERROR: Failed to copy file 'php_wikidiff2.ini' to '/etc/php.d/'!"
-	exit -3
+	echo "     ERROR: Failed to copy wikidiff2 module to module directory!"
+	popd
+	exit -5
+fi
+
+if [ ! -f /usr/lib64/php/modules/wikidiff2.so ]
+then
+	echo "     ERROR: Failed to install the WikiDiff2 PHP extension!"
+	popd
+	exit -6
+fi
+
+cp -f wikidiff2.ini /etc/php.d/
+RESULT=$?
+
+if [ $RESULT !=  0 ] || [ ! -f /etc/php.d/wikidiff2.ini ]
+then
+	echo "     ERROR: Failed to copy file 'wikidiff2.ini' to '/etc/php.d/'!"
+	popd
+	exit -7
 fi
 
 RESULT=`php -m | grep -c -i 'wikidiff2'`
 
 if [ $RESULT -eq 0 ]
 then
-	echo "     ERROR: The wikidiff2 PHP extension is does show up in loaded modules!"
-	exit -4
+	echo "     ERROR: The wikidiff2 PHP extension does show up in loaded modules!"
+	popd
+	exit -8
 fi
 
 echo "     OK: WikiDiff2 PHP extension installed!"
+popd
 exit 0
diff --git a/uesp-update-hostname b/uesp-update-hostname
--- a/uesp-update-hostname
+++ b/uesp-update-hostname
@@ -59,6 +59,15 @@ else
 	fi	
 fi
 
+hostnamectl set-hostname $HOSTNAME
+RESULT=$?
+
+if [ $RESULT != 0 ]
+then
+	echo "     ERROR: Failed to set the static host name to '$HOSTNAME'!"
+	exit -4
+fi
+
 echo "     OK: Updated host name to '$HOSTNAME'!"
 exit 0
 
diff --git a/uesp-update-sshd b/uesp-update-sshd
--- a/uesp-update-sshd
+++ b/uesp-update-sshd
@@ -60,11 +60,34 @@ else
 	fi
 fi
 
+RESULT=`egrep -ci "[#]?[ ^I]*ClientAliveCountMax[ ^I]+" $SSHCONF`
+
+if [ $RESULT > 0 ]
+then
+	sed -i "s:^[ ^I]*[#]*[ ^I]*ClientAliveCountMax[ ^I]*.*:ClientAliveCountMax 100:i" $SSHCONF
+
+	if [ $? != 0 ]
+	then
+		echo "     ERROR: Failed to update ClientAliveCountMax in '$$SHCONF'!"
+		exit -4
+	fi
+else
+
+	echo "ClientAliveCountMax 100" >> $SSHCONF
+
+	if [ $? != 0 ]
+	then
+		echo "     ERROR: Failed to add 'ClientAliveCountMax' to end of '$SSHCONF'!"
+		exit -5
+	fi
+fi
+
+
 # Fix possible permission issue
-chmod 711 /var/empty/sshd
+chmod 644 /var/empty/sshd
 chown root:root /var/empty/sshd
 
-/etc/init.d/sshd restart
+ service sshd restart
 
 echo "     OK: Updated the sshd configuration."
 exit 0
