salt minion setup

diff --git a/uesp-setup-saltminion b/uesp-setup-saltminion
--- a/uesp-setup-saltminion
+++ b/uesp-setup-saltminion
@@ -6,6 +6,9 @@ SHORTHOSTNAME=`hostname -s`
 
 echo "Setting up the salt minion..."
 
+# This is probably already done but just in case
+./uesp-yuminstall "salt-minion"
+
 echo "$LOCALHOSTNAME" > "$CONFIGPATH/minion_id"
 
 if [ $? != 0 ]
@@ -27,6 +30,15 @@ sed -i "s/^id:.*/id: $SHORTHOSTNAME/g" "$CONFIGPATH/minion.d/id.conf"
 if [ $? != 0 ]
 then
 	echo "     ERROR: Failed to modify the minion id.conf file!"
+	exit -4
+fi
+
+systemctl enable salt-minion
+systemctl start salt-minion
+
+if [ $? != 0 ]
+then
+	echo "     ERROR: Failed to start the salt.minion!"
 	exit -4
 fi
 
